### ISSUE TITLE
品技签无法正常签到

### ISSUE THREAD

**Issue by fl0w1nd** [wjf0214/qd-templates#179]
在本地部署的最新版签到框架，也部署了flaresolverr，但是签到时永远卡在第三步
![image](https://github.com/wjf0214/qd-templates/assets/97872569/babb2456-be85-4275-8e58-da33fe21cea3)
这是我的参数填写
![image](https://github.com/wjf0214/qd-templates/assets/97872569/dc05b2ab-ff6e-4a50-bd94-22101df161d4)

**Comment by wjf0214** [comment]
你框架和flaresolverr是在一个机器，一个网络下吗？

**Comment by fl0w1nd** [comment]
框架和flaresolverr都是群晖docker部署的

**Comment by wjf0214** [comment]
你签到任务点击模板。一个一个请求单独执行看看呢？看看那4个变量有没有正常获取到？
我这目前正常，而且没有其他人反馈有这个情况出现。
不确定什么原因导致的。

**Comment by fl0w1nd** [comment]
我在模板里单独执行试了下，一个个保存参数逐步执行，每次在第三个请求都会失败并且遇到相同的错误，前两个操作也确实获取了cookie并调用了flaresolverr，不知道是不是flaresolverr有什么环境配置要求
![image](https://github.com/wjf0214/qd-templates/assets/97872569/0cf2065e-c68d-4310-a5be-138fa5d0c740)
![image](https://github.com/wjf0214/qd-templates/assets/97872569/f3deb108-b5a6-4b4f-9b68-7f9698718cd0)

**Comment by wjf0214** [comment]
![image](https://github.com/wjf0214/qd-templates/assets/23102821/ea3e2035-323c-4ca8-9e0c-a79d62d95a3d)
你按这个图来，按顺序依次点击 转换和获取cf_clearance以及首页3这3个请求。
看看预览状态的参数是否都提取到。以及你看看cookie是否正常，cookie进行选中复制，有没有缺失遗漏。

**Comment by fl0w1nd** [comment]
第一个unicode转换测试没有问题
![image](https://github.com/wjf0214/qd-templates/assets/97872569/05d51302-17d9-42d6-baec-40e0ddfb4ef5)
第二个flaresolverr请求也获取了cookie的各变量没有问题
![image](https://github.com/wjf0214/qd-templates/assets/97872569/a817a2cd-18b1-408e-9f73-7dfb75aba796)
![image](https://github.com/wjf0214/qd-templates/assets/97872569/20cd69cc-6e53-4afa-b7c6-2ebae03d77b6)
第三个首页请求也获取了所有变量
![image](https://github.com/wjf0214/qd-templates/assets/97872569/18ecd382-8a60-41d4-b601-cdaef76c89c4)
但是测试时会有Enable JavaScript and cookies to continue的报错
![image](https://github.com/wjf0214/qd-templates/assets/97872569/8526c80d-f92e-4ebb-bff1-dc2afaeae7ba)
选中前三项使用网页最下端的测试的话只会有下面这种报错
![image](https://github.com/wjf0214/qd-templates/assets/97872569/1eb56f1d-7b87-46fd-8aca-a2bfd4aa64a2)
另外你上面发的那个图里的请求和我的有一点点不一样，首页的前后多了两个判断条件

**Comment by wjf0214** [comment]
我更新一下吧。之前加了个是否有cf盾的判断。有些人好像会不出现cf盾的问题。
从 flaresolverr 的返回结果来看，好像是cookie有问题。cookie好像失效了。你更新下cookie试试。。

**Comment by Sartner** [comment]
同样卡在这一步，手动模拟了一下请求，HTTP内的文本提示 Enable JavaScript and cookies to continue。
是不是因为站点加了JS检测导致，有什么方法能绕过吗

**Comment by fejich** [comment]
> 同样卡在这一步，手动模拟了一下请求，HTTP内的文本提示 Enable JavaScript and cookies to continue。 是不是因为站点加了JS检测导致，有什么方法能绕过吗

昨天部署下来测试都是正常的，用的项目里边最新版的模板
Flaresolverr 服务的 Docker 容器也是跑在同一个机器上
为了避免奇怪问题，三个容器都是使用 host 网络

docker-compose.yml
```
version: "3"

services:
  qd:
    image: dockerproxy.com/a76yyyy/qiandao
    # image: a76yyyy/qiandao:lite-latest
    container_name: qd
    depends_on:
      - redis
    network_mode: host
#    ports:
#      - "8923:80"
    volumes:
      - "./config:/usr/src/app/config"
    environment:
      # - QIANDAO_DEBUG=False
      # - MULTI_PROCESS=False
      # - AUTO_RELOAD=False
      # - GZIP=True
      # - BIND=0.0.0.0
      - PORT=8923
      # - QUEUE_NUM=50
      # - ENABLE_HTTPS=False
      # - ACCESS_LOG=True
      # - DOMAIN=
      # - USE_PYCURL=True
      # - ALLOW_RETRY=True
      # - DNS_SERVER=
      # - CURL_ENCODING=True
      # - CURL_CONTENT_LENGTH=True
      # - NOT_RETRY_CODE=301|302|303|304|305|307|400|401|403|404|405|407|408|409|410|412|415|413|414|500|501|502|503|504|599
      # - EMPTY_RETRY=True
      # - COOKIE_DAY=5
      # - JAWSDB_MARIA_URL=mysql://user:pass@localhost:3306/dbname?auth_plugin=
      - REDISCLOUD_URL=redis://127.0.0.1:6379
      # - TRACEBACK_PRINT=False
      # - PUSH_PIC_URL=https://fastly.jsdelivr.net/gh/qd-today/qd@master/web/static/img/push_pic.png
      # - PUSH_BATCH_SW=True
      # - PUSH_BATCH_DELTA=60
      # - WS_PING_INTERVAL=5
      # - WS_PING_TIMEOUT=30
      # - WS_MAX_MESSAGE_SIZE=10485760
      # - WS_MAX_QUEUE_SIZE=100
      # - WS_MAX_CONNECTIONS_SUBSCRIBE=30
      # - SUBSCRIBE_ACCELERATE_URL=jsdelivr_cdn
      # - DB_TYPE=sqlite3
      # - QIANDAO_SQL_LOGGING_NAME=qiandao.sql
      # - QIANDAO_SQL_LOGGING_LEVEL=WARNING
      # - QIANDAO_SQL_POOL_LOGGING_NAME=qiandao.sql.pool
      # - QIANDAO_SQL_POOL_LOGGING_LEVEL=WARNING
      # - QIANDAO_SQL_POOL_SIZE=5
      # - QIANDAO_SQL_MAX_OVERFLOW=10
      # - QIANDAO_SQL_POOL_PRE_PING=True
      # - QIANDAO_SQL_POOL_RECYCLE=3600
      # - QIANDAO_SQL_POOL_TIMEOUT=30
      # - QIANDAO_SQL_POOL_USE_LIFO=True
      # - REDIS_DB_INDEX=1
      # - QIANDAO_EVIL=1000
      # - EVIL_PASS_LAN_IP=True
      - PBKDF2_ITERATIONS=400
      - AES_KEY=binux
      - COOKIE_SECRET=binux
      # - CHECK_TASK_LOOP=500
      # - TASK_MAX_RETRY_COUNT=8
      # - DOWNLOAD_SIZE_LIMIT=5242880
      # - REQUEST_TIMEOUT=30.0
      # - CONNECT_TIMEOUT=30.0
      # - DELAY_MAX_TIMEOUT=29.9
      # - UNSAFE_EVAL_TIMEOUT=3.0
      # - PROXIES=
      # - PROXY_DIRECT_MODE=regexp
      # - PROXY_DIRECT=(?xi)\A([a-z][a-z0-9+\-.]*://)?(0(.0){3}|127(.0){2}.1|localhost|\[::([\d]+)?\])(:[0-9]+)?
      # - NEW_TASK_DELAY=1
      # - EXTRA_ONNX_NAME=
      # - EXTRA_CHARSETS_NAME=
      # - NEW_TASK_DELAY=1
      # - MAIL_SMTP=
      # - MAIL_PORT=465
      # - MAIL_SSL=True
      # - MAIL_USER=
      # - MAIL_PASSWORD=
      # - MAIL_FROM=${MAIL_USER}
      # - MAIL_DOMAIN=
      # - MAILGUN_KEY=
      # - USER0ISADMIN=True

  redis:
    image: dockerproxy.com/library/redis:alpine
    container_name: qd-redis
    command: ["--loglevel warning"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: host
#    ports:
#      - "6379:6379"
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    restart: unless-stopped 

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.dockerproxy.com/flaresolverr/flaresolverr
    container_name: qd-flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    network_mode: host
#    ports:
#      - "8191:8191"
    restart: unless-stopped
```
